/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.hm.gui;

import com.edu.hm.controllers.AttendanceController;
import com.edu.hm.controllers.EmployeeController;
import com.edu.hm.dto.AttendanceDTO;
import com.edu.hm.dto.EmployeeDTO;
import static com.edu.hm.gui.AddmissionForm.setDate;
import com.edu.hm.methods.AttendanceCheckMethods;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jinadi
 */
public class AttendanceForm extends javax.swing.JPanel {

    /**
     * Creates new form AddmissionForm
     */
    private ClockLabel withSecondsLable = new ClockLabel("withSeconds");
      private JLabel dateValLable;
    private Date date = new Date();
    private boolean isConstructorClosed = false;
    private DefaultTableModel dtm;
    public AttendanceForm() {
         this.dateValLable = new JLabel(setDate(date));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTodayAttendance = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        jLabel5.setText("employee ID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, 30));

        jTextField1.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 130, 30));

        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel27.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 255, 102));
        jLabel27.setText("valid");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 90, 50));

        jLabel10.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel10.setText("in time");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 70));

        jLabel1.setFont(new java.awt.Font("Raleway Light", 0, 24)); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel29.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 290, 30));

        jLabel22.setFont(new java.awt.Font("Raleway Thin", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 0));
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 240, 100));

        jLabel11.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel11.setText("short leave out");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, 70));

        jLabel25.setFont(new java.awt.Font("Raleway Thin", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 102, 0));
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 250, 80));

        jLabel9.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel9.setText("short leave in");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 70));

        jLabel23.setFont(new java.awt.Font("Raleway Thin", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 0));
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 250, 100));

        jLabel6.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel6.setText("out time");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 120, 70));

        jLabel24.setFont(new java.awt.Font("Raleway Thin", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 102, 0));
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 280, 100));

        tableTodayAttendance.setFont(new java.awt.Font("Raleway Light", 0, 14)); // NOI18N
        tableTodayAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "name", "in", "out"
            }
        ));
        jScrollPane1.setViewportView(tableTodayAttendance);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 830, 260));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("summary ");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, -1, -1));

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("total in");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("short leave");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("total out");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, -1, -1));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("0");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, -1, -1));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, -1, -1));

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Raleway Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("0");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, -1, -1));

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 160, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        try {
            jLabel27.setVisible(false);
           
            jLabel25.setText("");
            jLabel24.setText("");
            jLabel23.setText("");
            jLabel22.setText("");
            EmployeeDTO employee = EmployeeController.searchEmployeeDTO(jTextField1.getText());
            if (employee != null) {
                jLabel27.setVisible(true);
                jLabel29.setText(employee.getFirstName() + " " + employee.getLastName());
                jLabel29.setVisible(true);
                AttendanceDTO attendance = AttendanceController.getEmployeeAttendance(jTextField1.getText(), dateValLable.getText());
                String text = withSecondsLable.getText();
                char[] time = {text.charAt(0), text.charAt(1), text.charAt(3), text.charAt(4), text.charAt(6), text.charAt(7)};
                String timeInt = "";
                for (int i = 0; i < time.length;i++) {
                    timeInt += time[i];
                }
                if (attendance != null && Integer.parseInt(timeInt) >= 170000) {
                    jLabel25.setText(attendance.getInTime());
                    jLabel22.setText(attendance.getShortLeaveOutTime());
                    jLabel23.setText(attendance.getShortLeaveInTime());
                    jLabel24.setText(withSecondsLable.getText());
                    int otHours = AttendanceCheckMethods.getTimeHours(jLabel24.getText()) - AttendanceCheckMethods.getTimeHours("170000");
                    int outTimeMinutes = AttendanceCheckMethods.getTimeMinutes(jLabel24.getText());
                    if (outTimeMinutes > 45) {
                        otHours += 1;
                    }
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.updateAttendance(attendance);
                    jTextField1.setText("");
                } else if (attendance != null && attendance.getShortLeaveOutTime().equals("") && Integer.parseInt(timeInt) < 170000) {
                    jLabel25.setText(attendance.getInTime());
                    if (AttendanceController.getShortLeaveCount(jTextField1.getText()) > 2) {
                        AttendanceCheckMethods.setHalfDay(jTextField1, dateValLable);
                    } else {
                        jLabel22.setText(withSecondsLable.getText());
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                        AttendanceController.updateAttendance(attendance);
                        jTextField1.setText("");
                    }
                } else if (attendance != null && attendance.getShortLeaveOutTime() != null && Integer.parseInt(timeInt) < 170000) {
                    jLabel25.setText(attendance.getInTime());
                    jLabel22.setText(attendance.getShortLeaveOutTime());
                    jLabel23.setText(withSecondsLable.getText());
                    attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.updateAttendance(attendance);
                    jTextField1.setText("");
                } else if (attendance == null && Integer.parseInt(timeInt) > 81500 && Integer.parseInt(timeInt) < 93000) {
                    jLabel25.setText(withSecondsLable.getText());
                    jLabel22.setText("08.00.00");
                    jLabel23.setText(jLabel25.getText());
                    attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.markAttendanceIn(attendance);
                    jTextField1.setText("");
                } else if (attendance == null && Integer.parseInt(timeInt) > 93000) {
                    jLabel25.setText(withSecondsLable.getText());
                    AttendanceCheckMethods.setHalfDay(jTextField1, dateValLable);
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.markAttendanceIn(attendance);
                    jTextField1.setText("");
                } else {
                    jLabel25.setText(withSecondsLable.getText());
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.markAttendanceIn(attendance);
                    jTextField1.setText("");
                }
                AttendanceCheckMethods.setTodayAttendance(dateValLable, tableTodayAttendance);
                AttendanceCheckMethods.setTodaySummary(tableTodayAttendance, jLabel16, jLabel18, jLabel19);
                AttendanceCheckMethods.checkShortLeave(dateValLable);
            } else {
                
                jLabel29.setVisible(false);
                jTextField1.setText("");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.getStackTrace();
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        try {
            jLabel27.setVisible(false);
           
            jLabel25.setText("");
            jLabel24.setText("");
            jLabel23.setText("");
            jLabel22.setText("");
            EmployeeDTO employee = EmployeeController.searchEmployeeDTO(jTextField1.getText());
            if (employee != null) {
                jLabel27.setVisible(true);
                jLabel29.setText(employee.getFirstName() + " " + employee.getLastName());
                jLabel29.setVisible(true);
                AttendanceDTO attendance = AttendanceController.getEmployeeAttendance(jTextField1.getText(), dateValLable.getText());
                String text = withSecondsLable.getText();
                char[] time = {text.charAt(0), text.charAt(1), text.charAt(3), text.charAt(4), text.charAt(6), text.charAt(7)};
                String timeInt = "";
                for (int i = 0; i < time.length;i++) {
                    timeInt += time[i];
                }
                if (attendance != null && Integer.parseInt(timeInt) >= 170000) {
                    jLabel25.setText(attendance.getInTime());
                    jLabel22.setText(attendance.getShortLeaveOutTime());
                    jLabel23.setText(attendance.getShortLeaveInTime());
                    jLabel24.setText(withSecondsLable.getText());
                    int otHours = AttendanceCheckMethods.getTimeHours(jLabel24.getText()) - AttendanceCheckMethods.getTimeHours("170000");
                    int outTimeMinutes = AttendanceCheckMethods.getTimeMinutes(jLabel24.getText());
                    if (outTimeMinutes > 45) {
                        otHours += 1;
                    }
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.updateAttendance(attendance);
                    jTextField1.setText("");
                } else if (attendance != null && attendance.getShortLeaveOutTime().equals("") && Integer.parseInt(timeInt) < 170000) {
                    jLabel25.setText(attendance.getInTime());
                    if (AttendanceController.getShortLeaveCount(jTextField1.getText()) > 2) {
                        AttendanceCheckMethods.setHalfDay(jTextField1, dateValLable);
                    } else {
                        jLabel22.setText(withSecondsLable.getText());
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                        AttendanceController.updateAttendance(attendance);
                        jTextField1.setText("");
                    }
                } else if (attendance != null && attendance.getShortLeaveOutTime() != null && Integer.parseInt(timeInt) < 170000) {
                    jLabel25.setText(attendance.getInTime());
                    jLabel22.setText(attendance.getShortLeaveOutTime());
                    jLabel23.setText(withSecondsLable.getText());
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.updateAttendance(attendance);
                    jTextField1.setText("");
                } else if (attendance == null && Integer.parseInt(timeInt) > 81500 && Integer.parseInt(timeInt) < 93000) {
                    jLabel25.setText(withSecondsLable.getText());
                    jLabel22.setText("08.00.00");
                    jLabel23.setText(jLabel25.getText());
                        attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.markAttendanceIn(attendance);
                    jTextField1.setText("");
                } else if (attendance == null && Integer.parseInt(timeInt) > 93000) {
                    jLabel25.setText(withSecondsLable.getText());
                    AttendanceCheckMethods.setHalfDay(jTextField1, dateValLable);
                    attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.markAttendanceIn(attendance);
                    jTextField1.setText("");
                } else {
                    jLabel25.setText(withSecondsLable.getText());
                    attendance = new AttendanceDTO(EmployeeController.searchEmployeeDTO(jTextField1.getText()), dateValLable.getText(), jLabel25.getText(), jLabel22.getText(), jLabel23.getText(), jLabel24.getText(), 0);
                    AttendanceController.markAttendanceIn(attendance);
                    jTextField1.setText("");
                }
                AttendanceCheckMethods.setTodayAttendance(dateValLable, tableTodayAttendance);
                AttendanceCheckMethods.setTodaySummary(tableTodayAttendance, jLabel16, jLabel18, jLabel19);
                AttendanceCheckMethods.checkShortLeave(dateValLable);
            } else {
                
                jLabel29.setVisible(false);
                jTextField1.setText("");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AttendanceForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AttendanceForm.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        jLabel31.setVisible(false);
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
       
    }//GEN-LAST:event_jLabel1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableTodayAttendance;
    // End of variables declaration//GEN-END:variables
}
