/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.hm.gui;

import com.edu.hm.controllers.PatientController;
import com.edu.hm.controllers.TestController;
import com.edu.hm.controllers.TestDetailController;
import com.edu.hm.dto.PatientDTO;
import com.edu.hm.dto.TestDTO;
import com.edu.hm.dto.TestDetailDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jinadi
 */
public class TestDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form TestDetailForm
     */
    public TestDetailForm() {
        initComponents();
        loadTestCm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBlood = new javax.swing.JLabel();
        lblNic1 = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCons = new javax.swing.JLabel();
        cmbName = new javax.swing.JComboBox<>();
        cmbNu = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1020, 470));
        setPreferredSize(new java.awt.Dimension(1020, 470));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setText("blood group");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 217, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("date of birth");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 217, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("tel");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 217, 80));

        txtAddress.setEditable(false);
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 350, 90));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 217, 65));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("name ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 217, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("NIC");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 217, 60));

        txtPatientID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 340, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel10.setText("patient ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 217, 60));

        lblName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblName.setToolTipText("");
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 350, 40));

        lblBlood.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblBlood.setToolTipText("");
        jPanel2.add(lblBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 350, 40));

        lblNic1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblNic1.setToolTipText("");
        jPanel2.add(lblNic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 350, 40));

        lbltel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbltel.setToolTipText("");
        jPanel2.add(lbltel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 350, 40));

        lbldob.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbldob.setToolTipText("");
        jPanel2.add(lbldob, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 350, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel5.setText("test details");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 199, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel6.setText("test number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 136, 131, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel8.setText("result");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 251, 131, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel9.setText("price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 131, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel12.setText("test name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 192, 131, -1));

        lblCons.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblCons.setText("a");
        jPanel1.add(lblCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, 35));

        cmbName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNameItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 210, 30));

        cmbNu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNuItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, 70));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel14.setText("consultant");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 131, 35));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 210, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 130, 40));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
      serchPatient();
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void cmbNuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNuItemStateChanged
       cmbName.setSelectedIndex(cmbNu.getSelectedIndex());
       set();
    }//GEN-LAST:event_cmbNuItemStateChanged

    private void cmbNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNameItemStateChanged
     cmbNu.setSelectedIndex(cmbName.getSelectedIndex());
     set();
    }//GEN-LAST:event_cmbNameItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Date date=new Date();
            
            String tdid=date.getDate()+txtPatientID.getText();
            TestDTO dTO=TestController.searchTest(cmbNu.getSelectedItem().toString());
            PatientDTO patientDTO=PatientController.searchPatientDTO(txtPatientID.getText());
            String result=jTextArea1.getText();
            
            TestDetailDTO detailDTO=new TestDetailDTO(tdid, dTO, patientDTO, result, Double.parseDouble(txtPrice.getText()));
            boolean add=TestDetailController.addTest(detailDTO);
            if(add){
                JOptionPane.showMessageDialog(this,"test result added ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbName;
    private javax.swing.JComboBox<String> cmbNu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBlood;
    private javax.swing.JLabel lblCons;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNic1;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lbltel;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private void serchPatient() {
        try {
            PatientDTO patientDTO=PatientController.searchPatientDTO(txtPatientID.getText());
            lblNic1.setText(patientDTO.getNic());
            lblName.setText(patientDTO.getFirstName()+" "+patientDTO.getMiddleName()+" "+patientDTO.getLastName());
            lblBlood.setText(patientDTO.getBloodGrup());
            lbldob.setText(patientDTO.getDob());
            lbltel.setText(patientDTO.getTel()+"");
            txtAddress.setText(patientDTO.getAddress());
            lblCons.setText(patientDTO.getConsultantDTO().getEmployeeDTO().getFirstName()+" "+patientDTO.getConsultantDTO().getEmployeeDTO().getMiddleName()+" "+patientDTO.getConsultantDTO().getEmployeeDTO().getLastName());
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TestDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void loadTestCm() {
        try {
            ArrayList<TestDTO>arrayList=TestController.getTestDTOs();
            for (TestDTO testDTO : arrayList) {
                cmbName.addItem(testDTO.getDescription());
                cmbNu.addItem(testDTO.getTid());
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void set() {
        try {
            String id=(String) cmbNu.getSelectedItem();
            TestDTO  dTO=TestController.searchTest(id);
            txtPrice.setText(dTO.getPrice()+"");
        } catch (SQLException ex) {
            Logger.getLogger(TestDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
